### ISSUE TITLE
Chef server running with self signed cert

### ISSUE THREAD

**Issue by jaredmichaelwilliams** [conjurinc/summon-chefapi#1]
getting this error: `x509: certificate signed by unknown authority`

`Error fetching variable s3creds: Get https://url/organizations/bonobos/data/s3_creds/dev: x509: certificate signed by unknown authority`

Im assuming it doesnt read the certs from ~/.chef/trusted_certs

any thoughts?

**Comment by jaredmichaelwilliams** [comment]
I read through the go-chef code, and i added SkipSSL: true to the main chef config object when the environment variable CHEF_SSL_SKIP is true. Ill put a pull request in soon

**Comment by ghost** [comment]
Thanks for pointing this out. It looks like they already exposed insecure SSL as an option in the underlying go-chef lib: https://github.com/go-chef/chef/pull/23

In this case, we can use an env var like `CHEF_SKIP_SSL` to toggle this behavior.

**Comment by jaredmichaelwilliams** [comment]
Yeah i did that here: https://github.com/conjurinc/summon-chefapi/pull/2

**Comment by ghost** [comment]
Added in [v0.1.1](https://github.com/conjurinc/summon-chefapi/releases/tag/v0.1.1)

Details in PR #2
